### PR TITLE
format bat in prg style

### PR DESCRIPTION
**Pull request by JoseQuintas**
only format bat in prg style

### CODE REVIEW

**Comment by JoseQuintas** [comment]
Will use oohgaux.bat to reduce bats, then first step is include it on distro.

**Comment by fyurisich** [comment]
Please, explain me how is the user going to use this file.

**Comment by JoseQuintas** [comment]
User will not use it, but OOHG will.
I will organize one by one, using OOHGAUX.BAT to centralize all.

Example COMPILE.BAT
Today:
COMPILE.BAT test and call COMPILE30.BAT, COMPILE32.BAT, COMPILEXB.BAT
Test of external bat is usefull, because test HG_ROOT too. if exist %HG_ROOT%\compileXX.BAT

Next:
Will test %HG_ROOT%\OOHGAUX.BAT
this will ensure that HG_ROOT is set up correctly, and will be the starting point for moving routines into OOHGAUX.BAT.
the 3 BATs (compileXX) can already be erased after being moved, COMPILE.BAT will test only 1 BAT instead of 3 BATS.

Another example:
Too many BATs have a routine to compile a PRG.
Why too many routines? What of them is working?
I can create on OOHGAUX.BAT anything like this:

:COMPILE_PRG_HB30
   harbour PRGFILE parameters
   goto :END

 and on bats, call OOHGAUX COMPILE_PRG_HB30 prgfile

my idea is to go reducing the content of the bats, centering on OOHGAUX.BAT.
As in OOHGAUX.BAT will be divided into parts, the maintenance of all BATs will be easy, just change OOHGAUX.BAT.
All BATs will work on same way: if compile PRG works on one BAT, will works on another too.
This will make more visible what each BAT does, and will allow to decide what can be deleted.
At momment, seems that there are trash BATs - not used.

And if all routines becomes inside OOHGAUX.BAT, may be can limit to 3 BATs or less. 

Note: 
I will include test for %HG_ROOT%\OOHGAUX.BAT on all BATS, before new changes.

**Comment by JoseQuintas** [comment]
Seems you are changing distro to use hbmk2.
May be you can confirm how hbmk2 helps to make all on an easy way.

**Comment by fyurisich** [comment]
Please beware that the user can have the 3 different distros installed at the same time at C:\OOHG
And he can decide which one is going to use:
COMPILE HB32 myprg1
COMPILE HB30 myprg2
COMPILE XB myprg3

**Comment by fyurisich** [comment]
I don't know what you mean, I'm not changing distro to use hbmk2, I always use it for HB30 and HB32.

**Comment by JoseQuintas** [comment]
My mistake, you change only some lines of hbmk2.

**Pull request closed without merging**
